# Generated by Django 5.1.15 on 2026-07-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, default='Remote', max_length=255),
        ),
    ]
